### ISSUE TITLE
docker-compose run web rails new . --force --database=postgresql No funciona

### ISSUE THREAD

**Issue by diegoheg** [IIC2143-2018-2/project#1]
Cuando corro el comando del título recibo el siguiente error:
![image](https://user-images.githubusercontent.com/26411041/44274879-b76c2480-a219-11e8-99dc-7de81ff7ad81.png)
Siendo que el archivo existe y está configurado como lo especifica la ayudantía:
![image](https://user-images.githubusercontent.com/26411041/44275007-116cea00-a21a-11e8-8b6f-894b56c0fb71.png)
![image](https://user-images.githubusercontent.com/26411041/44275034-20ec3300-a21a-11e8-86e8-3e912e09318c.png)

Aclarar que estoy usando Docker Toolbox

**Comment by haroldmuller** [comment]
Hola,

podrías poner la configuración del Dockerfile, de docker-compose.yml y el nombre de la carpeta donde estás trabajando?

**Comment by diegoheg** [comment]
docker-compose.yml:
![image](https://user-images.githubusercontent.com/26411041/44369576-3c22a100-a4ad-11e8-9f41-d26cf51d48f2.png)
Path: 'D:\Docs\UNI\Sexto Semestre\Ingeniería de software\project\example'
Todos los archivos están en ese path (ahí use 'ls')

**Comment by haroldmuller** [comment]
El docker-compose.yml se ve bien, podrías postear el Dockerfile.

**Comment by Jiruiz2** [comment]
Hola, aprovecharé para preguntar por lo mismo. 
Me entrega el siguiente error:
![image](https://user-images.githubusercontent.com/26437497/44500762-96b02e80-a660-11e8-99a5-315352158cc4.png)

En mi carpeta tengo los siguientes archivos:
![image](https://user-images.githubusercontent.com/26437497/44500796-c101ec00-a660-11e8-9dff-3eb1591adbd3.png)

docker-compose.yml:
![image](https://user-images.githubusercontent.com/26437497/44500855-0aead200-a661-11e8-96e7-d4579de475e8.png)

Dockerfile:
![image](https://user-images.githubusercontent.com/26437497/44500864-1b9b4800-a661-11e8-926d-2deb7b266abc.png)

Gemfile:
![image](https://user-images.githubusercontent.com/26437497/44500877-28b83700-a661-11e8-92b7-234dbf507fe9.png)

**Comment by vacodoceo** [comment]
@Jiruiz2 , tu error se debe a que tu archivo `touch.env` debe llamarse `.env`.

**Comment by diegoheg** [comment]
Mi dockerfile:
![image](https://user-images.githubusercontent.com/26411041/44540361-f5b38900-a6dc-11e8-921c-7c4d2925d19e.png)

**Comment by vacodoceo** [comment]
@diegoheg no he podido encontrar un error en tus archivos, revisa que esté todo similar al repositorio de tu grupo, el cual cloné y pude configurar sin problemas.

Cuentanos como te va :smile:

**Comment by Pyralspite** [comment]
@diegoheg Tuve el mismo error con toolbox. Tienes que mover tu carpeta a C://Users/..../example. El problema es que VirtualBox solo tiene acceso a las carpetas en esa ubicación. 
Si quieres conservarlas en D: tienes que modificar unos archivos además de agregar D: como carpeta compartida. Lamentablemente perdí el link donde explicaban como hacerlo, pero no debe ser dificil encontrarlo. Ojo que no basta con agregar D: como carpeta compartida!
Suerte c:
