### ISSUE TITLE
Error con docker build y run para app

### ISSUE THREAD

**Issue by valerojasm** [IIC2143-2018-2/project#12]
Hola! Estoy intentando usar docker para la app hello world que hay que subir, y después de instalar y arreglar mil cosas sigo teniendo este error al hacer build o run:
![captura de pantalla 2018-08-27 a las 17 17 19](https://user-images.githubusercontent.com/37253682/44683698-66301200-aa1d-11e8-8f8d-9e753594d548.png)

he probado varios comandos distintos pero me sigue saliendo ese error. No tuve ningún problema al usar el ejemplo que subieron. Usé los mismos archivos y los puse en la carpeta de mi app, le cambié un path al dockerfile nomás, pero quizás hay que hacer algo más? Gracias!

**Comment by vacodoceo** [comment]
Hola! Puedes mostrar tu Dockerfile y Gemfile? Creo que el error va por ahi.

Saludos!

**Comment by valerojasm** [comment]
Hola, si!

El gemfile es el mismo que subieron, solo cambié la versión de ruby de "2.3.algo" a "2.3.1". El dockerfile ocupé el mismo que subieron también y no me funcionaba y ahora estoy usando otro que encontré en internet:

![captura de pantalla 2018-08-27 a las 17 45 51](https://user-images.githubusercontent.com/37253682/44685201-4995d900-aa21-11e8-9c11-6997b88f497d.png)


Ahora el proceso avanza un poco más y el error es:

![captura de pantalla 2018-08-27 a las 17 48 07](https://user-images.githubusercontent.com/37253682/44685247-68946b00-aa21-11e8-8f4c-de2f1acc4fa8.png)
![captura de pantalla 2018-08-27 a las 17 48 11](https://user-images.githubusercontent.com/37253682/44685248-68946b00-aa21-11e8-82b5-2e06eaf876cb.png)

**Comment by vacodoceo** [comment]
Al parecer tienes un problema de dependencias y/o versiones. Que te sale cuando haces `docker-compose build` con los archivos configurados tal como sale en la ayudantía 1? No debiera darte ningún problema con esa configuración.

**Comment by valerojasm** [comment]
El problema lo he tenido todo el rato, partiendo con la configuración inicial que pasaron en la carpeta example. Ahora los volví a poner y es exactamente lo mismo:

![captura de pantalla 2018-08-27 a las 18 01 50](https://user-images.githubusercontent.com/37253682/44686023-4f8cb980-aa23-11e8-98c3-cc8357a10bf7.png)

**Comment by valerojasm** [comment]
Logré arreglarlo y ahora mi problema es que se sale altiro. Todo bien con el build, pero después veo las imágenes con docker-compose ps y me sale que el status de mi web es exit 1, y cuando hago docker-compose up efectivamente sale con code 1.

docker-compose ps:
![captura de pantalla 2018-08-27 a las 18 32 57](https://user-images.githubusercontent.com/37253682/44687473-b4e2a980-aa27-11e8-832e-933fce77c741.png)

docker-compose up:
![captura de pantalla 2018-08-27 a las 18 33 12](https://user-images.githubusercontent.com/37253682/44687492-be6c1180-aa27-11e8-9d9a-17d0a4050b0a.png)

**Comment by vacodoceo** [comment]
Intenta con `docker-compose up -d`.
