### ISSUE TITLE
Relatos de usuario - Condiciones de satisfacción

### ISSUE THREAD

**Issue by javiinostroza** [IIC2143-2018-2/project#13]
Hola, en los relatos de usuario de la entrega 0, además de ingresar el rol de usuario, una meta y un beneficio, nos piden incluir **_"condiciones de satisfacción"_**.
A qué se refiere con ésto??

**Comment by vacodoceo** [comment]
Hola! Corresponde a como debes verificar que dicho relato está funcionando. En la clase 3a de Jaime Navon hay un pequeño ejemplo.

Saludos!
