### ISSUE TITLE
ERROR: No container found for web_1

### ISSUE THREAD

**Issue by augustoas** [IIC2143-2018-2/project#15]
Al ejecutar docker-compose exec web rake db:create se me cae. 

![captura](https://user-images.githubusercontent.com/11396572/44702325-4cb4b780-aa69-11e8-8c0d-a792498482cb.JPG)

**Comment by haroldmuller** [comment]
Hola!
Si te fijas, el contenedor web no está corriendo. Sube un pantallazo después de correr `docker-compose logs web`. A priori se me ocurre que no seteaste la bdd en el archivo `config/databse.yml`, fijate en la ayudantía 1.

**Comment by augustoas** [comment]
Me funcionó ! Gracias !

**Comment by haroldmuller** [comment]
Cómo lo solucionaste? Le puede servir a tus compañeros! @augustoas

**Comment by naquiroz** [comment]
~Hola! En mi caso lanzó en mismo error pero en Ubuntu (18.04) y me asegure que web estuviera encendido.
Adjunto imagen del log~
![image](https://user-images.githubusercontent.com/29825816/44744840-70651580-aadc-11e8-9bf7-3cd8d9669567.png)

~Como puedo solucionarlo?~

**Edit: Me faltaba un espacio en el `command` en docker-compose.yml!**

**Comment by antoniarlx** [comment]
@augustoas Como lo solucionaste? Me pasa lo mismo ahora.

**Comment by augustoas** [comment]
Borré todo e hice todo denuevo paso por paso. Pero los comandos que están en “example”. Los de la ayudantía nunca me sirvieron. Y envés de usar exec use run. Suerte !!

**Comment by aurodriguez** [comment]
Cuales son los comandos de example?

**Comment by aurodriguez** [comment]
Te refieres a los archivos de example?
