### ISSUE TITLE
Error al hacer install bundle

### ISSUE THREAD

**Issue by SarahEverke** [IIC2143-2018-2/project#16]
Siguiendo este tutorial https://devcenter.heroku.com/articles/getting-started-with-rails5 ,
cuando escribo install bundle
tengo el siguiente error (mi computador es mac):

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.

**Comment by haroldmuller** [comment]
que comando corres exactamente? Recuerda que siempre debes anteponer el `docker-compose exec web`

**Comment by SarahEverke** [comment]
Tengo una carpeta con todos los archivos creados en la ayudantía 1, después sigo los pasos del tutorial que mencioné antes y cuando escribo  install bundle, me sale el error

**Comment by SarahEverke** [comment]
super, me funciono con lo que dijiste! gracias
