### ISSUE TITLE
Error en Rubocop

### ISSUE THREAD

**Issue by mundurragac** [IIC2143-2018-2/project#17]
Intento corregir el error 'Metrics/LineLength: Line is too long. [89/80]' y me arroja el error 'Style/BlockDelimiters: Avoid using {...} for multi-line blocks.'

Que puedo hacer, ya que si corrijo uno me arroja el otro

**Comment by haroldmuller** [comment]
Hola,
La verdad no se exactamente como arreglar eso en particular, pero no te recomiendo cambiar el largo por linea, ya que eso se escapa de lo ya visto en programación avanzada (PEP8). Mejor busca la manera correcta de continuar una linea en la siguiente.

**Comment by criscv94** [comment]
Hola,
El segundo error lo puedes solucionar usando `do` y `end` en vez de `{...}`. 
Por ejemplo usa
```ruby
@users.each do |user|
    print user.name
end
```
en vez de
```ruby
@users.each { |user|
    print user.name
}
```
Los bloques `{...}` normalmente se usan para cosas mas cortas, por eso si no alcanza en una linea.. usa `do` y `end`
Avisa si eso resuelve el problema 😃

**Comment by mundurragac** [comment]
Si funciono! 
Muchas gracias
