### ISSUE TITLE
Duda Fecha de entrega

### ISSUE THREAD

**Issue by jmopaso** [IIC2143-2018-2/project#18]
Hola!
En el enunciado de la entrega 0 dice en la sección **5 de entrega**
> La fecha de entrega es 29 de Agosto, 19:59.

Sin embargo, en el calendario del curso se señala que la entrega era hasta hoydia (28 de Agosto) hasta las 19:59.
¿Cual fecha de entrega será la definitiva?

**Comment by haroldmuller** [comment]
Hola,
Al comienzo dice 28 de Agosto, además se recordó en 2 avisos que era el 28 de Agosto y está el calendario del curso en el repositorio del proyecto.

**Comment by jmopaso** [comment]
@haroldmuller 
Gracias por la aclaración, será posbile que para la próxima vez se cambien las fechas cuando esto suceda? Así se evitan otras confusiones.
