### ISSUE TITLE
Duda con rake db:create

### ISSUE THREAD

**Issue by meretamal** [IIC2143-2018-2/project#19]
Es necesario, cada vez que levanto mi aplicación, correr docker-compose exec web rake:create??

**Comment by IsaacConDosA** [comment]
Hola! 
Ese comando es para crear las bases de datos del proyecto, por lo tanto solo se corre una vez al principio. Después de esto, quedan creadas y no es necesario volver a ejecutar ese comando. 
Saludos

**Comment by haroldmuller** [comment]
Hola!
Agregando a lo que comenta Isaac, para que puedas trabajar de manera más pulcra una vez ya corrido el comando `docker-compose up` la idea es que ocupen los comandos `docker-compose start` y `docker-compose stop` para levantar y bajar la aplicación. De esta manera mantendrá solo una instancia del contenedor y no destruirá la bdd.
Saludos,
