### ISSUE TITLE
Error docker-compose up

### ISSUE THREAD

**Issue by marianaortega1** [IIC2143-2018-2/project#20]
Hola! 
Me funcionaba todo perfecto y no cambié nada y ahora al hacer docker-compose up me tira este error:

C:\Users\Mariana\Documents\UC\2018-2\Ing de Software\grupo-25>docker-compose up
Starting grupo-25_postgres_1 ... error

ERROR: for grupo-25_postgres_1  Cannot start service postgres: driver failed programming external connectivity on endpoint grupo-25_postgres_1 (90a8db57220c279abf53123c3a4867ad16eaf8990772474de4117d41ce6132ce): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32958:tcp:172.21.0.2:5432: input/output error

ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint grupo-25_postgres_1 (90a8db57220c279abf53123c3a4867ad16eaf8990772474de4117d41ce6132ce): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32958:tcp:172.21.0.2:5432: input/output error
ERROR: Encountered errors while bringing up the project.

Ya me había pasado antes y tuve que eliminar docker y hacer absolutamente todo de nuevo y quiero evitar eso por si sigue pasando más adelante y tengo más avanzado el proyecto.
No pude encontrar algo que lo solucionara en internet. 

Si hago el docker-compose run web rails new . --force --database=postgresql me tira este error:

 C:\Users\Mariana\Documents\UC\2018-2\Ing de Software\grupo-25>docker-compose run web rails new . --force --database=postgresql
Starting grupo-25_postgres_1 ... error

ERROR: for grupo-25_postgres_1  Cannot start service postgres: driver failed programming external connectivity on endpoint grupo-25_postgres_1 (75f34ac82fd2fb05a0ae72ba51276440912cf7343fd3658db1043dae1192bbfb): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32968:tcp:172.21.0.2:5432: input/output error

ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint grupo-25_postgres_1 (75f34ac82fd2fb05a0ae72ba51276440912cf7343fd3658db1043dae1192bbfb): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32968:tcp:172.21.0.2:5432: input/output error
ERROR: Encountered errors while bringing up the project.

Gracias!
Mariana

**Comment by vacodoceo** [comment]
Hola! Me tinca que debe ser que dejaste otra aplicación corriendo en el localhost, es decir, hiciste `docker-compose up` sin hacer `docker-compose stop` posteriormente. Haz `docker-compose ps` para ver si hay mas servicios corriendo, si es así intenta detenerlos con `docker-compose stop [nombre del servicio]`.

**Comment by mfviglioni** [comment]
Buenas tardes. Les dejo para saber si me pueden colaborar?

tengo este docker-compose:
version: '2'
services:
  mongo:
    image: mongo
    volumes:
    - $PWD/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  nodejs:
    image: 'node:8'
    user: 'nodejs'
    depends_on:
      - mongo
    working_dir: $PWD/app
    volumes:
      - $PWD/app:/home/node/app
    expose:
    - '8080'
    environment:
    - NODE_ENV:produccion
    command: bash -c "npm install && npm run dev"


y el error que me arroja es:

docker@docker-VirtualBox:~/Docker/Nodejs-Mongo$ docker-compose up -d
Creating nodejs-mongo_mongo_1 ... done
Creating nodejs-mongo_nodejs_1 ... error

ERROR: for nodejs-mongo_nodejs_1  Cannot start service nodejs: unable to find user nodejs: no matching entries in passwd file

ERROR: for nodejs  Cannot start service nodejs: unable to find user nodejs: no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.

-- Agradecería cualquir ayuda por fvor ! gracias
