### ISSUE TITLE
Que son los itinerarios?

### ISSUE THREAD

**Issue by naquiroz** [IIC2143-2018-2/project#21]
Hola! :wave: 

En el enunciado hablan de **Itinerarios**, sin embargo, en ningún momento se explica o detalla que es un usuario y cual es la interacción del usuario con estos. Además, no se habla de crear **CRUD** para los `Hoteles`, `Lugares` o `Restaurantes`. Está bien esas partes del enunciado?

Si la respuesta es sí, a que se refieren con Itinerarios y porque no hay que crear  **CRUD**  de lo anterior?

Saludos  :v:

**Comment by haroldmuller** [comment]
Hola!
Los usuarios pueden publicar itinerarios. Con itinerarios se refiere a un recorrido a visitar ciertos lugares, hoteles, etc. dentro de una ciudad. Tomalos como un tipo de publicación. Las publicaciones podrían ser una *review* de un restaurant, un itinerario a realizar, etc. 
El proyecto en algunos puntos queda abierto a como ustedes quieran modelarlo. Si quieren agregar los `Hoteles`, `Lugares` y `Restaurantes` como entidades dentro de su app se puede, pero también estaría correcto dejarlos solo dentro de las publicaciones, depende completamente de como modelen esa parte del proyecto. Por otro lado, algunos **CRUD** (los mencionados en el enunciado) son los mínimos a realizar. 
Espero que te quede un poco más claro esta parte.

Saludos,
