### ISSUE TITLE
Error Docker, Service 'web' failed to build:

### ISSUE THREAD

**Issue by beayancan** [IIC2143-2018-2/project#22]
Hola, estaba intentado trabajar con los comandos que entregaron para la **ayudantía 4**, sin embargo, arroja un error al intentar ejecutarlo. Trabajé en la base **example** que nos habían dado en la ayudantia anterior.
* El error que me arroja
![pantalla](https://user-images.githubusercontent.com/37157874/45097175-969c3e00-b0f8-11e8-88bf-bf99057300f3.png)

* El archivo Gemfile
![gemfile](https://user-images.githubusercontent.com/37157874/45097184-9a2fc500-b0f8-11e8-8aef-0dcaa4365474.png)

* Dockerfile
![dockerfile](https://user-images.githubusercontent.com/37157874/45097190-9e5be280-b0f8-11e8-97e2-c329eb954509.png)

*Docker_compose
![docker_compose](https://user-images.githubusercontent.com/37157874/45097196-a3b92d00-b0f8-11e8-957c-254293985657.png)

**Comment by haroldmuller** [comment]
Hola,

por lo que veo en tu Gemfile, no haz creado el proyecto. Para hacer esto debes correr el siguiente comando: `docker-compose run web rails new . --force -d=postgresql` y luego correr `docker-compose build`. Después podrás comenzar a realizar lo que se ha visto en las últimas ayudantías.

**Comment by beayancan** [comment]
Lo intenté y arroja algo parecido
![captura de pantalla 64](https://user-images.githubusercontent.com/37157874/45097771-f6dfaf80-b0f9-11e8-99af-3b64921c5998.png)

**Comment by haroldmuller** [comment]
Hola,

Ya me di cuenta del error. Fijate en el archivo `docker-compose.yml`y el archivo `Dockerfile`. En el `docker-compose.yml` tienes que la carpeta en el contenedor se llama `ayudantia4` y en el `Dockerfile`se llama `example`. Esto genera que no encuentre la carpeta dentro del contenedor porque está buscando la carpeta `ayudantia4`, pero en realidad se llama `example`. Haz que los nombres sean el mismo y corre `docker-compose build`, con eso debería funcionar.

Saludos,

**Comment by beayancan** [comment]
De igual forma cambie a *ayudantia4* el nombre en Dockerfile y docker_compose, pero obtengo un resultado similar con ambos comandos
![captura de pantalla 67](https://user-images.githubusercontent.com/37157874/45098902-63f44480-b0fc-11e8-94f0-f169b8040b2f.png)

**Comment by haroldmuller** [comment]
Me tinca que al ya estar creado el contenedor, no está reconociendo la nueva configuración. Te recomiendo borrar el contenedor y volverlo a generar.
