### ISSUE TITLE
Error certificado 

### ISSUE THREAD

**Issue by vamussuto** [IIC2143-2018-2/project#23]
Hola, he intentado correr los comandos para trabajar con docker y me arroja el siguiente error. He buscado soluciones pero no logró arreglarlo.
![error](https://user-images.githubusercontent.com/37153558/45130796-861fae00-b160-11e8-9e50-8696f2806d8d.PNG)

**Comment by haroldmuller** [comment]
Hola!
Podrías decirme tu sistema operativo(versión de este), versión de _Docker_ y contar un poco los pasos que seguiste hasta el error.

**Comment by vamussuto** [comment]
Windows 10 Education versión 1803 (versión del sistema operativo 17134.254)
Docker version 18.06.1
Por lo que busqué, el problema creo que se originó porque antes tenía Docker Toolbox. Hice las soluciones de estos links:
https://github.com/docker/for-win/issues/1746
https://apilevel.wordpress.com/2017/11/23/docker-for-windows-certificate-error-solution/

Luego de eso ya no me aparece el error anterior, pero me arroja este error.
![error2](https://user-images.githubusercontent.com/37153558/45178267-96c93600-b1eb-11e8-9dd6-87adb13a544c.PNG)
Hice la instrucción para instalar las gemas faltantes (sin ningún error) pero continúa arrojando lo mismo cuando pongo el comando de la imagen. No he logrado entender si este nuevo error se relaciona con el anterior o es algo a parte.
