### ISSUE TITLE
ERRORES en iniciar app con Docker 

### ISSUE THREAD

**Issue by antoniarlx** [IIC2143-2018-2/project#24]
Hola! La primera vez que use Docker me funciono crear la app de Rails. Lo cerre y ahora al hacerlo de nuevo me aparecen los siguientes errores. (Re inicialize Docker)  

Primero, mientras corro **docker-compose run web rails new . --force --database=postgresql**, me aparecen los siguientes errores, en partes separadas del codigo:

<img width="525" alt="screen shot 2018-09-06 at 16 35 22" src="https://user-images.githubusercontent.com/28511788/45180787-df382200-b1f2-11e8-818b-86e450d39fd6.png">

<img width="488" alt="screen shot 2018-09-06 at 16 36 04" src="https://user-images.githubusercontent.com/28511788/45180913-448c1300-b1f3-11e8-80bf-922f0444f41a.png">

Luego, sigo las instrucciones de la ayudantia, y finalmente despues de varios intentos me funciono conectarme a Yay you are on Rails, pero necesito saber de que se trata el error arriba, o si no es relevante. 

Muchas gracias!

**Comment by haroldmuller** [comment]
Hola,
no te preocupes por esos mensajes en particular. Algunos como el de `Teletype` es por una extensión de _Atom_. No deberían ser problemas para que puedas seguir corriendo comandos de _Docker_.
Saludos,

**Comment by antoniarlx** [comment]
Ok. Muchas gracias!

*Antonia Rodríguez Landeta*
*Ingeniería Civil Industrial mención Tecnologías de Información *
Pontificia Universidad Católica de Chile





2018-09-06 17:20 GMT-03:00 Harold Müller <notifications@github.com>:
