### ISSUE TITLE
No me ""corre"" el repositorio example

### ISSUE THREAD

**Issue by agustinkrebs** [IIC2143-2018-2/project#25]
Hola.

Quisiera saber cómo puedo hacer para correr el repositorio example en mi computador. Al clonarlo, e iniciar un servidor en la carpeta correspondiente (rails s) el programa me tira errores al abrir http://localhost:3000/

¿Cómo debería ser el proceso para que me corra en mi computador? Ya tengo docker instalado

Por favor

**Comment by haroldmuller** [comment]
Hola!

Recuerda que este semestre se está utilizando _Docker_ y por eso mismo el repo de la ayudantía está generado con _Docker_. Por otro lado, corrí el repo y si esta funcionando. Fijate que tengas creada la _db_ y corrida las migraciones.

Saludos,
