### ISSUE TITLE
Duda atributos

### ISSUE THREAD

**Issue by marianaortega1** [IIC2143-2018-2/project#26]
Hola!

Tenemos una duda sobre los atributos de una entidad. Para ruby on rails se puede tener que un atributo de una entidad sea una tabla? Por ejemplo en el punto 4.Atributos mínimos en 4.1 Usuario se tiene Lugares Favoritos. Básicamente si hiciéramos una consulta a otra tabla obtendríamos los lugares favoritos de un usuario. ¿Es correcto que el resultado de esa consulta (una tabla) sea el atributo Lugares favoritos y que se vaya actualizando? 
En ese caso qué tipo sería ese atributo? (Ej. string,  integer, etc)

Saludos,
Mariana

**Comment by IsaacConDosA** [comment]
Lo correcto en ese caso, es que el usuario tenga como referencia sus lugares favoritos (en la ayudantía 4 se vio cómo hacerlo). 
Puedes buscar sobre Rails Associations para ver cuáles son las opciones posibles al momento de crear relaciones entre clases.
