### ISSUE TITLE
ERROR: for postgres  Cannot start service postgres

### ISSUE THREAD

**Issue by paula-ds** [IIC2143-2018-2/project#27]
Hola!, tengo un problema con docker y no encuentro ninguna solución que me ayude, cuando hago docker-compose build y docker-compose up en la rama master no tengo ningún problema pero cuando me cambio de rama con git checkout users, se hace docker-compose up bien, al final sale:

Successfully built b46ad6bdb9ab
Successfully tagged grupo-05_web:latest

Y si luego hago docker-compose up sale:

Starting grupo-05_postgres_1 ... error

ERROR: for grupo-05_postgres_1  Cannot start service postgres: driver failed programming external connectivity on endpoint grupo-05_postgres_1 (63d8e33ca49e502cbbaf1ef8d4ad79132bc9c381434db364914ee52583aff8f7): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32831:tcp:172.20.0.2:5432: input/output error

ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint grupo-05_postgres_1 (63d8e33ca49e502cbbaf1ef8d4ad79132bc9c381434db364914ee52583aff8f7): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32831:tcp:172.20.0.2:5432: input/output error
ERROR: Encountered errors while bringing up the project.

Si alguien me pudiera ayudar lo agradecería, saludos.

**Comment by haroldmuller** [comment]
Hola!
Podrías dejar un _screenshot_ de tu `Dockerfile` y `docker-compose.yml`para ver la configuración que estás ocupando.

**Comment by paula-ds** [comment]
Hola! creo que ahora me funcionó, al menos ya no me sale ese error así que espero que esté todo bien, gracias!
