### ISSUE TITLE
error en rails db:migrate

### ISSUE THREAD

**Issue by julioag** [IIC2143-2018-2/project#28]
Hola estoy intentando inicializar el devise, pero en el último paso donde tengo que correr la migración me aparece esto : 
![image](https://user-images.githubusercontent.com/26441194/45401463-19f0ee80-b627-11e8-9b35-6bedd09fd89a.png)

Como puedo solucionar lo anterior?? he seguido cada paso de las ayudantías pasadas.

**Comment by IsaacConDosA** [comment]
Al parecer no has creado la base de datos. Corre docker-compose run web rails db:create y cuéntame cómo te va.
Saludos

**Comment by julioag** [comment]
Gracias! si me sirvió al final
