### ISSUE TITLE
error exited with code 1

### ISSUE THREAD

**Issue by SarahEverke** [IIC2143-2018-2/project#29]
Hola,

al usar docker-compose up tengo el siguiente error 

> proyecto_web_1 exited with code 1

¿Qué puedo hacer?

Saludos

**Comment by haroldmuller** [comment]
Hola!
Revisa en la carpeta `tmp/pids/` si hay un archivo `server.pid`. Si este existe borralo y vuelve a correr `docker-compose start` (equivalente a `docker-compose up`). Esto debería funcionar. Sino funciona, deja un _screenshot_ del error para poder verlo completo.

Saludos,
