### ISSUE TITLE
Git kraken no me deja hacer pull ni push

### ISSUE THREAD

**Issue by dvogaz** [IIC2143-2018-2/project#3]
Al momento de hacer pull a mi repositorio del proyecto, me lanza el siguiente error:
![issue](https://user-images.githubusercontent.com/26395763/44482397-955e1200-a61e-11e8-9379-0ca5874024b9.png)
Autoricé correctamente la aplicación, no entiendo que esta mal 😞

**Comment by haroldmuller** [comment]
Hola!
Me llegó la solicitud de para darle permiso a Git Kraken. No lo daremos porque no es una práctica que queremos fomentar en el curso. La idea es que ganen experiencia con Git.
