### ISSUE TITLE
Heroku problemas al subir

### ISSUE THREAD

**Issue by CmPoblete** [IIC2143-2018-2/project#31]
Hola, cuando subimos el foro a heroku, tira un error en la pagina. Suponemos que esto es por la gema devise al agregar  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }  en development.rb  (tambien la agregamos en production.rb pero con el host de nuestra aplicacion).

Tambien nos pasa que ahora cuando intentamos volver a subir algo a heroku nos tira el error Precompiling assets failed y ya no sabemos que hacer

**Comment by IsaacConDosA** [comment]
Hola!
¿En production.rb qué escribieron exactamente?

**Comment by phaeussler** [comment]
Hola!,
Creo que pusumos esto:
config.action_mailer.default_url_options = { host: 'http://the-traveler-grupo28.herokuapp.com'}

**Comment by IsaacConDosA** [comment]
Puedes subir una fotos de los logs de heroku (en la misma página de heroku pueden revisar a qué me refiero)?

**Comment by CmPoblete** [comment]
Ya logre arreglarlo.
Gracias
