### ISSUE TITLE
Carrierwave, subir imágenes

### ISSUE THREAD

**Issue by fgbruna** [IIC2143-2018-2/project#33]
Se puede usar la gema [Carrierwave](https://github.com/carrierwaveuploader/carrierwave) para manejar las publicaciones con imagenes?

**Comment by haroldmuller** [comment]
Hola!
A priori te diría que si está permitida. Fijate bien donde almacena los archivos dado que el servidor de _Heroku_ al ser gratuito, borra los archivos temporales al final de cada día (el servidor debe "dormir" 6 horas).

**Comment by fgbruna** [comment]
Ok gracias!, lo tendré en cuenta.
