### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by SarahEverke** [IIC2143-2018-2/project#34]
Hola,

actualmente tenemos una branch llamada develop, donde tenemos los archivo actualizados del programa.
¿Cuándo y cómo tengo que hacer merge de develop con master?

Saludos!

**Comment by MrEarle** [comment]
Hola!
Lamento la demora. La idea es que el merge de develop con master sea cuando lo que tienes en develop esté listo para poner en produccion. En el caso de este proyecto, esto seria para cada entrega.
