### ISSUE TITLE
Heroku no reconoce la app

### ISSUE THREAD

**Issue by vjlira** [IIC2143-2018-2/project#35]
Hola, tengo un problema al hacer " git push heroku" , probé incluso con "heroku buildpacks:set heroku/ruby" y no me lo reconoce. 
![error heroku](https://user-images.githubusercontent.com/26437431/45578733-b13d8800-b859-11e8-8e83-3d9981cab293.png)

**Comment by criscv94** [comment]
Hola! Lamento lo tarde, el problema es porque tienes tu proyecto dentro de otra carpeta, por lo que heroku no reconoce tu app. La idea es que tu proyecto este en el _root_ de tu repo. Avísame si eso soluciona tu problema :smile:
