### ISSUE TITLE
Problema crear base de datos 

### ISSUE THREAD

**Issue by SarahEverke** [IIC2143-2018-2/project#37]
Hola,

al escribir en la terminal docker-compose run  web rails db:create, tengo el siguiente error:

> Starting proyecto_postgres_1 ... done
Could not find i18n-1.1.0 in any of the sources
Run `bundle install` to install missing gems.

Después escribo docker-compose run  web rails bundle install y obtengo 

> Starting proyecto_postgres_1 ... done
Could not find i18n-1.1.0 in any of the sources
Run `bundle install` to install missing gems.

¿Qué puedo hacer?

Saludos!

**Comment by IsaacConDosA** [comment]
Hola!
Debes construir la aplicación de nuevo. Para eso debes correr el
Comando docker-compose build.
Saludos

**Comment by SarahEverke** [comment]
Eso era, gracias!
