### ISSUE TITLE
Docker: Hyper-V no encontró ningún conmutador virtual con el nombre "DockerNAT".

### ISSUE THREAD

**Issue by meretamal** [IIC2143-2018-2/project#38]
Hola.
Estoy corriendo Docker for Windows y, hasta el momento, no había tenido problemas para usarlo, pero ahora, al tratar de iniciarlo, me aparece que "Hyper-V no encontró ningún conmutador virtual con el nombre "DockerNAT".". Intenté reseteando Docker y reinstalándolo pero sigo teniendo el mismo error, por lo que supongo que debe ser un problema con Hyper-V. ¿Alguna sugerencia?
Gracias de antemano

**Comment by vacodoceo** [comment]
Hola!

Googleando al parecer alguien pudo solucionarlo apagando Hyper-V, reiniciando el PC, prendiendo Hyper-V, reiniciando el PC, y luego abriendo Docker y utilizando los contenedores de Linux.
