### ISSUE TITLE
Gemas permitidas/ no permitidas para el proyecto semestral

### ISSUE THREAD

**Issue by jerosalazar** [IIC2143-2018-2/project#39]
# Restricciones

Para consultar sobre una gema o servicio deberán comentar este issue con una pregunta de la siguiente forma:

>  ¿Puedo utilizar la librería "nombre_librería" para hacer “explicación-de-lo-que-quiero-hacer”?

## Permitidas
- ```Devise```
- ```CanCanCan```
- ```CarrierWave```
- ```Acts-as-votable```
- ```Rolify```
- ```Active Storage```
- ```Bootstrap```
- ```Faker```
- ```Will_paginate```
- ```Rinku```
- ```Geocoder```
- ```Open_weather```
- ```Redcarpet```
- ```Chartkick```
- ```Rails_admin```
- ```Active_admin```
- ```Cocoon```

## No Permitidas
- ```Ransack```
- ```Acts_as_follower```
- ```Acts_as_favoritor```
- ```Rapidfire```

**Comment by B-Dominguez** [comment]
¿Puedo utilizar la librería bootstrap para hacer manejo del front-end?

**Comment by jerosalazar** [comment]
@B-Dominguez si, hay una ayudantía de eso

**Comment by meretamal** [comment]
¿Puedo usar paperclip para subir las fotos de usuario?

**Comment by vacodoceo** [comment]
> ¿Puedo usar paperclip para subir las fotos de usuario?

@meretamal Se recomienda fuertemente utilizar Active Storage en lugar de paperclip ya que esta última está deprecada :)

**Comment by lechodiman** [comment]
Hola, ¿puedo utilizar

- `will_paginate`: para la paginación
- `ransack`: para realizar búsqueda a través de muchos modelos e implementarlo en el buscador
- `faker`: para generar datos y seeds a la base de datos
- `acts_as_favoritor`: para agregar ciertos posts o ciudades a favoritos
?

**Comment by jerosalazar** [comment]
```will_paginate``` y ```faker``` si se pueden, ```ransack``` no estará permitido. ```favoritor``` está en conversación, avisaré lo antes posible.

**Comment by vamussuto** [comment]
Hola, puedo usar "rinku" para agregar enlaces (hipervínculos) a las publicaciones y "geocoder" para agregar ubicación (ayuda a encontrar latitud y longitud)

**Comment by MrEarle** [comment]
@vamussuto Rinku y Geocoder si se pueden.

**Comment by lechodiman** [comment]
@jerosalazar  en relación a mi pregunta anterior, ¿por qué no se puede usar `ransack`?, siendo que lo que facilita en el desarrollo es más o menos lo mismo que las otras gemas. En mi caso particular lo usé solo para ` @countries = Country.ransack(name_cont: params[:q]).result(distinct: true) `. Frente a esto, también quiero preguntar si se puede usar alguna alternativa a `ransack`, como `searchkick`  o si debo realizar la lectura de la query a mano.

**Comment by fedetaladriz** [comment]
> > ¿Puedo usar paperclip para subir las fotos de usuario?
> 
> @meretamal Se recomienda fuertemente utilizar Active Storage en lugar de paperclip ya que esta última está deprecada :)

@vacodoceo Hola! Para Usar Active Storage al parecer necesitamos rails 5.2, y tenemos instalado rails 5.1.5. No hay problema con cambiar de version de rails, cierto?

**Comment by SarahEverke** [comment]
> > > ¿Puedo usar paperclip para subir las fotos de usuario?
> > 
> > 
> > @meretamal Se recomienda fuertemente utilizar Active Storage en lugar de paperclip ya que esta última está deprecada :)
> 
> @vacodoceo Hola! Para Usar Active Storage al parecer necesitamos rails 5.2, y tenemos instalado rails 5.1.5. No hay problema con cambiar de version de rails, cierto?

¿Se puede modificar la versión de rails a 5.2?

**Comment by vacodoceo** [comment]
@fedetaladriz , @SarahEverke si pueden modificar su version de rails, siempre teniendo cuidado que sus dependencias soporten la version de Rails.

**Comment by beayancan** [comment]
Hola, se puede utilizar `acts_as_follower` para poder seguir a otros usuarios ?

**Comment by Calomi** [comment]
Hola se puede usar "jQuery Raty" para hacer el input de rating como las tipicas 5 estrellitas de valoracion?

**Comment by MrEarle** [comment]
> Hola, se puede utilizar `acts_as_follower` para poder seguir a otros usuarios ?

@beayancan  no, no se puede.

**Comment by Pipelao** [comment]
Hola, al final se puede ocupar act _as_favoritor??

Gracias de ante mano.

**Comment by SarahEverke** [comment]
Hola,

puedo usar open-weather para ver el clima de cada ciudad/país?
puedo usar redcarpet para que las publicaciones funcionen con markdown?

**Comment by IsaacConDosA** [comment]
Hola!
Sí se pueden usar esas dos.
Saludos

**Comment by IsaacConDosA** [comment]
@Pipelao no se puede

**Comment by SaritaGP** [comment]
Hola, se puede usar chartkick para realizar unos gráficos?

**Comment by IsaacConDosA** [comment]
@SaritaGP si se puede. Saludos!

**Comment by Jiparavich** [comment]
Hola! Se puede usar rails_admin para ayudar al manejo del admin?

**Comment by vamussuto** [comment]
Hola, se puede usar rapidfire para crear las encuestas?

**Comment by jjaguillon** [comment]
Hola. Se puede utilizar la gema active_admin, para el manejo de la administración.

**Comment by jerosalazar** [comment]
@Jiparavich @vamussuto @jjaguillon 
```rails_admin```y ```active_admin``` si se pueden. ```rapidfire``` no

**Comment by eitandv** [comment]
Hola! 
Estábamos pensando en utilizar la gema "cocoon" para poder acceder a un numero ilimitado de respuestas para una encuesta sin utilizar JS. ¿Esta permitido esto?
¡Gracias de antemano!

**Comment by jerosalazar** [comment]
@jjaguillon @vamussuto @Jiparavich 
Las de admin si se pueden ocupar, rapidfire no

**Comment by criscv94** [comment]
@eitandv sí pueden usar `cocoon`

**Comment by Calomi** [comment]
hola!, al final se puede usar jQuery Raty?, es un plugin q convierte el campo de input de rating en 5 estrellitas.
y se puede usar mini_magick para hacer un resize a las imagenes?

**Comment by criscv94** [comment]
@Calomi sí puedes usar `jQuery Raty` y `mini_magick`
