### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by savelozo** [IIC2143-2018-2/project#4]
Hola!

Cuando intento crear el archivo con las variables de entorno dice lo siguiente:

![image](https://user-images.githubusercontent.com/8712664/44530379-98134280-a6c4-11e8-8423-ee7c351adb2e.png)

He buscado algunas soluciones para poder darle atributos de admin a mi user (como chown, por ejemplo), pero no lo he logrado. Qué podría hacer al respecto?

**Comment by haroldmuller** [comment]
Hola,
`touch` es un comando de Unix para crear archivos desde la terminal. El equivalente de Windows está especificado en esta [publicación](https://stackoverflow.com/questions/30011267/windows-equivalent-of-touch-i-e-the-node-js-way-to-create-an-index-html).

**Comment by savelozo** [comment]
Lo sé, si busqué un poco antes de publicar la issue. Intenté de todas formas desde la terminar de windows y no de docker directamente en la carpeta donde debería estar el .env, sin embargo, me sale el mismo mensaje:

![image](https://user-images.githubusercontent.com/8712664/44532620-e2e38900-a6c9-11e8-94d6-a92a3dc47219.png)

**Comment by haroldmuller** [comment]
Ya entendí, el archivo `.env` tiene que estar en el root de tu aplicación. O sea tiene que estar al mismo nivel que está el archivo Gemfile o Dockerfile en tu repo.

**Comment by savelozo** [comment]
Claro, mi drama es que cuando intento crear dicho archivo en la carpeta es cuando explota jaja entonces ahí es cuando quedo medio colgado.

**Comment by haroldmuller** [comment]
y cuándo estás en la carpeta base del proyecto que comando corres? deja un pantallazo del comando junto al mensaje que te da.
