### ISSUE TITLE
Sistema no reconoce gema nokogiri después de haberla instalado

### ISSUE THREAD

**Issue by agustinkrebs** [IIC2143-2018-2/project#40]
Hola.

Luego de haber hecho `bundle install` y `gem install nokogiri-1.8.5`, el sistema sigue respondiendo con el siguiente error:
`Could not find nokogiri-1.8.5 in any of the sources`
`Run bundle install to install missing gems.`

Por favor ayuda, este error me prohibe hacer scaffolds

**Comment by haroldmuller** [comment]
Hola!

Estás instalando la gema en tu computador, pero no en el contenedor.

Para instalar la gema dentro de tu contenedor tienes 2 opciones. La primera es correr `docker-compose build` o sino correr la app con `docker-compose start` y luego correr `docker-compose exec web bundle`.

**Comment by IsaacConDosA** [comment]
Hola!
¿La pusiste en el Gemfile también?
Saludos
