### ISSUE TITLE
Problemas al hacer docker-compose up: could not open directory "pg_tblspc": No such file or directory

### ISSUE THREAD

**Issue by agustinkrebs** [IIC2143-2018-2/project#41]
Hola.

Al hacer `docker-compose build` y luego `docker-compose up`, mi terminal me arroja el siguiente error:
`db_1   | 2018-10-10 22:34:28.427 UTC [1] FATAL:  could not open directory "pg_tblspc": No such file or directory`

Algunas soluciones de internet decían que bastaba con crear esos directorios, pero al crearlos, el terminal decía que ya existían.

Importante destacar que debe ser algo relacionado a mi computador, dado que en el computador del integrante del grupo que modificó los archivos, sí funcionaba. Por otro lado, cuando yo modificaba archivos, luego mi amigo tenía el mismo error en su computador.

¿Qué se puede hacer al respecto?

**Comment by vacodoceo** [comment]
Hola!

Al final este problema se debía en parte a que tenían mal configurados los archivos "base" de Docker no? (Los que había que crear para la primera entrega)
