### ISSUE TITLE
Problema development.log

### ISSUE THREAD

**Issue by savelozo** [IIC2143-2018-2/project#42]
Hola, al intentar hacer el merge de mi rama el arcivho development.log me genera problemas, aún siendo que no debería subirse ya que está agregado en el gitignore.

![image](https://user-images.githubusercontent.com/8712664/46908172-0fab6400-cef5-11e8-8003-be6631508b75.png)

Además me indica el error en prácticamente todo el archivo. Qué puedo hacer al respecto? :)

**Comment by jerosalazar** [comment]
Como lo solucionaron?
