### ISSUE TITLE
ActiveRecord::PendingMigrationError 

### ISSUE THREAD

**Issue by javiinostroza** [IIC2143-2018-2/project#43]
Hola, cuando ingreso a localhost:3000 me aparece este error (antes no pasaba)
![screen shot 2018-10-13 at 4 33 22 pm](https://user-images.githubusercontent.com/26410892/46909363-61f58080-cf07-11e8-82f3-716d0228f660.png)

He intentado con 
1. `docker-compose run web  bin/rails db:migrate RAILS_ENV=development `
2. `docker-compose run web bundle exec rake db:create db:migrate`
3. `docker-compose exec web rake db:migrate`
Pero sigo teniendo el mismo problema.
Al ingresar cualquiera de los 3 comandos, la consola arroja: 
> PG::DuplicateTable: ERROR:  relation "pais" already exists

**Comment by IsaacConDosA** [comment]
Hola, eso pasa porque tienes una migración que crea la tabla paises. Pero ya existe en tu base de datos, por lo que no tiene sentido agregarla dos veces. 
Probablemente la migración sea inútil porque ya está repetida. 
Saludos

**Comment by javiinostroza** [comment]
Hola, entiendo que la migración es innecesaria de ahí la confusión. No entiendo por qué al entrar a la página aparece ActiveRecord::PendingMigrationError 😭

**Comment by IsaacConDosA** [comment]
Ese error siempre aparece cuándo tienes migraciones que aun no has corrido con `... db:migrate`. Si las corrieras te dejaría de aparecer ese error, el problema es que como esa migración está mala, entonces nunca corres las migraciones bien.

**Comment by javiinostroza** [comment]
Sii ahí funcionó! Muchas gracias!!!
