### ISSUE TITLE
Error rubocop

### ISSUE THREAD

**Issue by SarahEverke** [IIC2143-2018-2/project#47]
Hola,

al correr Rubocop tengo el siguiente error:

![screen shot 2018-10-30 at 5 00 08 pm](https://user-images.githubusercontent.com/30681133/47746676-47403d00-dc65-11e8-8991-570b031ad0e4.png)

¿Qué puedo hacer?
Saludos!

**Comment by jerosalazar** [comment]
Hola, intenta correr solo ```rubocop```
