### ISSUE TITLE
instalar gema

### ISSUE THREAD

**Issue by javiinostroza** [IIC2143-2018-2/project#49]
Hola, para instalar una gema debo instalar todas sus dependencias?
Llevo mucho rato intentando instalar Cancancan y minimagick.
Una vez que corro bundle, aparece 
```
Bundle complete! 22 Gemfile dependencies, 83 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
```

Pero cuando quiero seguir trabajando y corro cualquier otro código, aparece 

```
Could not find [NOMBRE DE ALGUNA GEMA] in any of the sources
Run `bundle install` to install missing gems.
```
Generalmente la gema que no se pudo encontrar es una dependencia de la que intenté instalar o es la dependencia de la dependencia, etc.

Entonces mi duda es, para instalar una sola gema, debería instalar como 30 más? Es decir, cada dependencia con todas sus dependencias y así sucesivamente?

**Comment by IsaacConDosA** [comment]
Hola!
Con qué comando estás instalando las gemas exactamente?
Saludos

**Comment by javiinostroza** [comment]
Noo, disculpa!  El problema está en la gema mime-types.

Primero instalé la gema carrierwave 
`docker-compose run web gem install carrierwave`
e hice los pasos a seguir en su [página de github](https://github.com/carrierwaveuploader/carrierwave)

Cuando hago `docker-compose run web rails generate uploader Avatar`
aparece
Error: `Could not find mime-types-data-3.2018.0812 in any of the sources`

En mi Gemfile puse: `gem 'mime-types', require: 'mime/types/full'` [(github mime-types)](https://github.com/mime-types/ruby-mime-types)

Luego corro `docker-compose run web bundle `

Finalmente hago `docker-compose run web rails generate uploader Avatar`
y vuelve a salir el mismo error D:

**Comment by javiinostroza** [comment]
Hola, ya solucioné el problema. Gracias!
