### ISSUE TITLE
ERROR: No container found for web_1

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2143-2018-2/project#5]
Hola! 
Seguí todos los pasos de la ayudantía, pero al crear la base de datos me sale el siguiente error:
![image](https://user-images.githubusercontent.com/26395403/44545530-b80a2c80-a6eb-11e8-9f3c-61ed18b97d76.png)
Me podrían explicar que esta pasando?

Gracias!

**Comment by haroldmuller** [comment]
Hola!
Tienes el contenedor corriendo? Corre el comando `docker-compose ps`. Si el estado no es up, no podrás correr los comandos con exec. Primero tienes que correr `docker-compose start` y luego el comando que trataste de correr.

**Comment by fedetaladriz** [comment]
Si lo tengo corriendo :( Me tira lo siguiente:
![image](https://user-images.githubusercontent.com/26395403/44559616-a93e6c80-a721-11e8-8cf8-b2d19bc0c46d.png)
Busqué lo del estado "Exit 1" pero no encontré nada que me sirviera

**Comment by haroldmuller** [comment]
Podrías correr el comando `docker-compose logs web` y tomar un screenshot de lo que aparezca. Este comando sirve para ver los logs del contenedor.

**Comment by fedetaladriz** [comment]
Me tira lo siguiente:
![image](https://user-images.githubusercontent.com/26395403/44591323-d166b380-a793-11e8-91db-31b79962af5a.png)

**Comment by fedetaladriz** [comment]
Ya lo solucioné! Al parecer era porque al ejecutar el comando "docker-compose up" no le había puesto -d al final jajaja gracias!!

**Comment by augustoas** [comment]
Me pasa lo mismo pero no logro solucionarlo con -d. Todavía me aparece "No container found for web_1" cuando corro el comando docker-compose exec web rake db:create
