### ISSUE TITLE
Viernes horario ayudantía

### ISSUE THREAD

**Issue by SarahEverke** [IIC2143-2018-2/project#55]
Hola,

¿el viernes habrá ayudantía o sala de ayuda para responder dudas del proyecto? 

Saludos

**Comment by fedetaladriz** [comment]
+1

**Comment by haroldmuller** [comment]
Hola, perdón lo tarde del aviso, pero no habrá. Cualquier duda dejen una issue y trataremos de responderla lo antes posible.
