### ISSUE TITLE
Asigancion de atributos en "create" en controlador

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2143-2018-2/project#56]
Hola!

Para nuestro proyecto, en los posts podemos crear comentarios. Para esto, tenemos el render del form de estos en la vista de cada post. La asignación del usuario a este comentario la teníamos en el controlador de este ultimo, en el método create:
`  

    @post = Post.find(params[:post_id])

    @commentary = @post.commentaries.create(commentary_params)

    @commentary.user = current_user`

Sin embargo, algo esta pasando que no se está guardando este atributo. Al mostrar los comenatarios en la show de los posts, estuve probando y me di cuenta que commentary.user era nil. 

Ya hice la relación one-to-many entre posts y comentarios y la columna en comentarios me aparece en el schema, por lo que no habria problema con eso. 

Busqué en muchas partes en internet, pero no encontré nada y he estado mucho rato pegado con esto. Alguien sabe cual puede ser el problema?
Gracias!!

**Comment by IsaacConDosA** [comment]
Hola
Estas haciendo
`@commentary.save` despues de eso de casualidad?

Saludos

**Comment by fedetaladriz** [comment]
> Hola
> Estas haciendo
> `@commentary.save` despues de eso de casualidad?
> 
> Saludos

Muchisimas gracias @ifcarrera !! Ese era el problema! Al parecer borré esa linea y no me di cuenta!
