### ISSUE TITLE
Duda entrega relatos de usuario

### ISSUE THREAD

**Issue by jmopaso** [IIC2143-2018-2/project#6]
Hola!
Tengo una duda con respecto al formato de entrega de los relatos de usuario, ya que en la seccion 5 del enunciado se indica:
> en la carpeta llamada **relatos** deben incluir el/los documentos de relatos de usuario

¿Qué se refiere exactamente a los documentos de relatos de usuario? podriamos poner simplemente un link que redirija a *trello* donde tengamos ahí los relatos de usuario.

**Comment by haroldmuller** [comment]
Hola!

No, deben entregar un pdf con los relatos de usuario y su condición de satisfacción. Esto porque tiene que quedar un registro inalterable, pero después ustedes tendrán que pasarlas al Trello para poder ocupar el kanban durante el semestre.
