### ISSUE TITLE
Error al correr Docker

### ISSUE THREAD

**Issue by meretamal** [IIC2143-2018-2/project#7]
Hola, al tratar de abrir Docker (Windows), me dice: "Hardware assisted virtualization and data execution protection must be enabled in the BIOS. " Traté de buscar como habilitarlo pero solo encontré respuestas para habilitar Hyper-V, lo cual Docker ya hizo. Si alguien sabe algo, se lo agradecería infinitamente.

**Comment by haroldmuller** [comment]
Hola!

Qué versión Windows tienes instalado en tu pc y qué versión de Docker estás tratando de instalar?

**Comment by meretamal** [comment]
Windows 10 Pro y Docker for Windows CE

**Comment by meretamal** [comment]
Hola, logré encontrar como activar la virtualización desde la BIOS. De todos modos, muchas gracias!!
