### ISSUE TITLE
no funciona localhost:300 

### ISSUE THREAD

**Issue by jotramon** [IIC2143-2018-2/project#9]
hola, tengo un problema, segui al pie de la letra las instrucciones de la ayundantia para la aplicacion en docker, incluso esta funcionando por lo que se ve
![image](https://user-images.githubusercontent.com/26410776/44605336-48fe0800-a7bf-11e8-887f-9c5f91e081a0.png)

pero al ver en chrome y distintos navegadores, no muestra nada

![image](https://user-images.githubusercontent.com/26410776/44605382-777be300-a7bf-11e8-80da-931c7af9963d.png)
 que puede ser?

**Comment by vacodoceo** [comment]
Hola ! Al estar corriendo Docker en una maquina virtual tus contenedores no estan corriendo de forma nativa en Windows, sino mediante la maquina virtual que utiliza una IP distinta a la del localhost. Esta IP te la especifican apenas inicias el Docker Quickstart Terminal.

![docker_ip](https://user-images.githubusercontent.com/17888204/44672805-ee9fba00-a9ff-11e8-891f-7c24d4013ff2.JPG)

Intenta ingresando al puerto 3000 de dicha IP.

[Fuente](https://stackoverflow.com/questions/41208782/docker-localhost-process-not-working-on-windows)

**Comment by beayancan** [comment]
Hola, disculpa tengo la misma duda ¿De qué forma podría ingresar al puerto? ¿De igual forma es algún navegador?
